### PR TITLE
Revert "WIP: Windowless Setup"

### PR DESCRIPTION
**Pull request by ghost**
Reverts NSLS-II-LIX/lixdc#1

### CODE REVIEW

**Comment by ghost** [comment]
:dash: :hankey:

**Comment by hhslepicka** [comment]
Go to hell @arkilic ! 😛

**Comment by ghost** [comment]
hahahah @klauer caught a big fish here

**Comment by klauer** [comment]
?

**Comment by arkilic** [comment]
He thought I reverted the functional PR that he is presenting to management :grinning:

**Pull request closed without merging**
