### PR TITLE
Windowless Setup

### PR DESCRIPTION
**Pull request by hhslepicka**

### CODE REVIEW

**Comment by ghost** [comment]
@hhslepicka Could you attach some screenshots? I would like to attach it to amostra documentation.

**Comment by hhslepicka** [comment]
It is still WIP, so there are some tweaks that I need to do! The search and import are working fine.
Here is an example of the find filling the table with sample information.
screen shot 2016-05-12 at 11 29 00 am

**Comment by ghost** [comment]
Excellent, thanks!

**Comment by ghost** [comment]
How did you merge the WIP? haha

**Comment by hhslepicka** [comment]
My repo, my rules! 😝

**Comment by ghost** [comment]
Very humble

**Pull request merged**
